import Providers from "@/lib/providers/Providers";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Swiper JS
import { Toaster } from "sonner";
import "swiper/css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medic Panda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <AppRouterCacheProvider>
          <body className={inter.className}>{children}</body>
        </AppRouterCacheProvider>
        <Toaster position="top-center" />
      </html>
    </Providers>
  );
}
