import { Box, Button, Typography } from "@mui/material";
import Link from "next/link";

import bgImage from "@/assets/about.png"; // Assuming image is optimized and available
import { Metadata } from "next";
import JoinUsSection from "./Components/JoinUsSection";
import OurMissionSection from "./Components/OurMissionSection";
import TeamMemberSection from "./Components/TeamMemberSection";

// Styles
const heroSectionStyle = {
  position: "relative",
  height: "60vh",
  backgroundImage: `url(${bgImage.src})`,
  backgroundSize: "cover",
  backgroundPosition: "center",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "#fff",
  textAlign: "center",
  padding: "0 20px",
  "&::before": {
    content: '""',
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0, 0, 0, 0.6)",
  },
  zIndex: 1,
};

const heroTextStyle = {
  position: "relative",
  zIndex: 2,
  backgroundColor: "rgba(255, 255, 255, 0.1)",
  padding: "20px",
  borderRadius: "12px",
};

// meta data
export const metadata: Metadata = {
  title: "About Us -medicPanda",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <Box display="flex" flexDirection="column" minHeight="100vh">
      {/* Hero Section */}
      <Box sx={heroSectionStyle}>
        <Box sx={heroTextStyle}>
          <Typography variant="h2" gutterBottom>
            Welcome to Our Medicine Shop
          </Typography>
          <Typography variant="h6">
            Your trusted partner for reliable, affordable healthcare solutions.
          </Typography>
          <Button
            variant="contained"
            size="large"
            component={Link}
            href="/products"
          >
            Explore Our Products
          </Button>
        </Box>
      </Box>

      {/* Mission and Values Section */}
      <OurMissionSection />

      {/* Our Team Section */}
      <TeamMemberSection />

      <JoinUsSection />
    </Box>
  );
};

export default AboutPage;
